### ISSUE TITLE
 window is not defined [gatsby-js and netlify]

### ISSUE THREAD

**Issue by Gervwyk** [bitworking/react-gsap#1]
I'm testing react-gsap with gatsby and deploying it with netlify, running into this error:
 
```
4:15:49 PM:   8366 | function PlugInSvgDraw () {
4:15:49 PM: > 8367 |   var _gsScope = typeof module !== "undefined" && module.exports && typeof global !== "undefined" ? global : this || window; //helps ensure compatibility with AMD/RequireJS and CommonJS/Node
4:15:49 PM:        | ^
4:15:49 PM:   8368 |   (_gsScope._gsQueue || (_gsScope._gsQueue = [])).push(function () {
4:15:49 PM:   8369 |
4:15:49 PM:   8370 |     // from https://github.com/juliangarnier/anime/blob/master/anime.js
4:15:49 PM: 
4:15:49 PM:   WebpackError: ReferenceError: window is not defined
```

Maybe you can change the condition to test if `window` is defined:
https://github.com/gatsbyjs/gatsby/issues/309

Really like how you structured these components!

**Comment by bitworking** [comment]
Thanks for testing and sending this issue. SSR compatibility is on my list and I hope I can fix it today and push a new release.

**Comment by bitworking** [comment]
I've added a simple window check and tested it in Gatsby. It should work now in v1.0.13.

**Comment by Gervwyk** [comment]
Thanks its working!
