### ISSUE TITLE
Adding Label support

### ISSUE THREAD

**Issue by stevengrimaldo** [bitworking/react-gsap#12]
Hello!
Thank you for a great package so far. I see in your TODO file that you plan on or want to add in the `addLabel` capability, is that something you plan on doing anytime soon? i have a use case for it now.

Use Case:

I have a wrapper element that contains children and i'm animating in each child item but then at the end of the timeline animating out the wrapper as a whole, and correct me If i'm wrong but doesn't each tween get added to the timeline in the order in which it appears?

All that to say since i'm wrapping each child item with the wrapper and the wrapper is in a tween i'm worried that the fade out will happen first and not last so i was hoping to add a position to it using labels.

Unless you can think of a better way of accomplishing what i'm trying to do. Here is a codepend of pure gsap timeline so you can see what i'm trying to do and then convert to react-gsap.

https://codepen.io/srgrimaldo/pen/zYxaYGr

**Comment by bitworking** [comment]
Yes it's possible with the new version: https://bitworking.github.io/react-gsap/src-components-timeline#label-support
