### ISSUE TITLE
Timeline playState props not working

### ISSUE THREAD

**Issue by Nalrarang** [bitworking/react-gsap#17]
I am trying to use Timeline but PlayState Props doesn't seem to work.
Here is an example implementation:
```javascript
<Timeline
  target={
    <div className='image_wrap'>
        <img ... />
    </div>
   }
   playState={isPlaying ? PlayState.play : PlayState.stop}
>
    <Tween to={{ opacity: 1 }} duration={0.5} />
    <Tween to={{ x: '455px' }} duration={0.8} />
    <Tween to={{ opacity: 0 }} duration={0.5} />
</Timeline>
```

In Controls, Props of PlayState work properly.
Is there something I am missing or wrong?

**Comment by bitworking** [comment]
I've tested it and it works for me. I would need to see where isPlaying is coming from. Please try this example:

```javascript
import { Tween, Timeline, PlayState } from 'react-gsap';

const TimelinePlayState = () => {
  const [playing, setPlaying] = React.useState(false);
  const [progress, setProgress] = React.useState(0);

  return (
    <>
      <Timeline
        target={<div style={{ width: '100px', height: '100px', background: '#ccc' }} />}
        playState={playing ? PlayState.play : PlayState.pause}
        totalProgress={progress}
        paused={false}
      >
        <Tween from={{ opacity: 0 }} to={{ opacity: 1 }} duration={2} />
        <Tween to={{ x: '200px' }} />
        <Tween to={{ rotation: 180 }} position="+=1" />
      </Timeline>
      <button onClick={() => setPlaying(!playing)}>{playing ? 'Pause' : 'Play'}</button>
      <div>
        <input
          type="range"
          min="0"
          max="1"
          step="0.001"
          value={progress}
          onChange={event => setProgress(parseFloat(event.target.value))}
        />
      </div>
    </>
  );
};
```

**Comment by Nalrarang** [comment]
The code in the example works fine.
I think there is a problem with my code. 😂
Thank you.

**Comment by CSMR-DB** [comment]
The `paused` prop is causing issues when trying to create a [Advanced Multiple Targets](https://bitworking.github.io/react-gsap/src-components-timeline#advanced-multiple-targets) composition*. It prevents any animation ([CodeSandbox demo here](https://codesandbox.io/s/nervous-panini-p51e8?file=/src/App.tsx)) from being started. If 'paused' is not provided, the animation ignores the `playState`. Why have both props (albeit `paused` not being as explicit) when it seems they can get in each other's way?

\* Using Controls still works in this situation
