### ISSUE TITLE
Tween.set

### ISSUE THREAD

**Issue by chrisgannon** [bitworking/react-gsap#20]
Is there a way to `set` a property without using a `to` Tween with a duration of 0?

So this:

`<Tween to={{ transformOrigin:"50% 50%" }} duration={0} />`

becomes this:

`<Tween set={{ transformOrigin:"50% 50%" }} />`

**Comment by bitworking** [comment]
Hmm..the default duration is 1 if you omit it. I don't want to change it because of backward compatibility. But I could provide a set prop for this. There is also a set method in the gsap Tween object which is essentially a to tween with the duration of 0.

**Comment by chrisgannon** [comment]
I’m not asking to change anything. Simply add in a `.set` method, just like the GSAP API. Currently to achieve this I have to do a tween with a duration of 0

**Comment by bitworking** [comment]
Yes, that's what the gsap docs says: https://greensock.com/docs/v3/GSAP/gsap.set()

But I keep it in mind for the next version.

**Comment by chrisgannon** [comment]
> Hmm..the default duration is 1

Just a heads up - the default duration for a GSAP 3.0 tween is now 0.5 seconds. In GSAP 2.x it was 1 second.
