### ISSUE TITLE
Character spacing in SplitChars is incorrect

### ISSUE THREAD

**Issue by chrisgannon** [bitworking/react-gsap#21]
Check out this demo:

https://codesandbox.io/s/flamboyant-fermi-4qqwx?file=/src/App.js

The grey text BELOW is just a DIV of text to show the correct spacing.

**Comment by bitworking** [comment]
Yes, it's because the space is not rendered in a wrapper component. I don't want the space to be animated. But just give a surrounding div the same font-size (40px) as the wrapper and you should be fine.

**Comment by chrisgannon** [comment]
Perfect thanks!
