### ISSUE TITLE
iOS 13.3 Safari Browser. Draw problem

### ISSUE THREAD

**Issue by bbg** [bitworking/react-gsap#24]
Hi @bitworking ;

I have 2 circles, one dotted and the other flat. The dotted circle looks flat on iOS 13.3 version. No problem in 13.4 version. 

"https://codepen.io/batuhangoksu/pen/ZEbwByP" Another example I did here was done directly with GSAP and it works without problems in iOS 13.3 version.

"https://codesandbox.io/s/react-gsap-nested-circle-chart-w9xbb?file=/next.config.js" Here you will find the example I made with the React-GSAP library. You will see that it makes my dotted circle straight. The problem is experienced in iOS 13.3 and below.

Can you help me with this?

<img width="483" alt="Screen Shot 2020-06-17 at 15 44 01" src="https://user-images.githubusercontent.com/13348876/84901379-128c2e00-b0b4-11ea-8655-62d4924519da.png">
<img width="480" alt="Screen Shot 2020-06-17 at 15 44 11" src="https://user-images.githubusercontent.com/13348876/84901388-1455f180-b0b4-11ea-93d3-68afea0da21f.png">

**Comment by bitworking** [comment]
This seems to be a gsap or Browser bug and not related to this lib.
