### ISSUE TITLE
Tween delay

### ISSUE THREAD

**Issue by muhmushtaha** [bitworking/react-gsap#25]
I have multiple tweens and I need to run a tween when another tween is completed and it seems the Tween doesn't take a delay prop, How I can manage the tweens order?

I tried position, stagger but I didn't manage to do it.

Any suggestion?

**Comment by garmjs** [comment]
@muhmushtaha please check the documentation https://bitworking.github.io/react-gsap/src-components-tween if you can't manage to get it working please share your code

**Comment by bitworking** [comment]
The Tween components takes the delay prop. It's not a typed prop but gets passed to the gsap tween. Else you could also wrap them with a Timeline component.

**Comment by muhmushtaha** [comment]
> The Tween components takes the delay prop. It's not a typed prop but gets passed to the gsap tween. Else you could also wrap them with a Timeline component.

I tried to pass the delay as prop to the Tween component but it seems the delay not ready yet, I checked the library files and I saw that there are resting the delay to 0 when they pass the props to the gsap tween vars.

I managed to solve it using Scrollscene and GASP libraries. 
@bitworking

**Comment by bbg** [comment]
@muhmushtaha Did you try it like the example I gave. If you haven't tried, can you try

`
<Tween from={{ opacity: 0, delay: 4 }} to={{ opacity: 1, delay: 4 }} duration={1} ease="Power1.in(1)">
---
</Tween>
`

**Comment by muhmushtaha** [comment]
> @muhmushtaha This is how you can make delays. I use it like this.
> 
> ```
> <Tween from={{ opacity: 0, delay: 4 }} to={{ opacity: 1, delay: 4 }} duration={1} ease="Power1.in(1)">
> ---
> </Tween>
> ```

Thank you, this worked. I was passing the delay as prop to the Tween while I have to add it as you said. @bbg

**Comment by obiknows** [comment]
can someone update the docs to show this is possible? I didn't know delays were possible until reading this issue
