### ISSUE TITLE
How to set timeline target to different child div in a same wrapper?

### ISSUE THREAD

**Issue by dennisloh95** [bitworking/react-gsap#3]
For example

<Controller>
<Scene>
{(progress)=>(
<Timeline totalProgress={progress} >
<div class="wrapper">
<div class="child1"/>
<div class="child2"/>
</div
</Timeline>
)}
</Scene>
</Controller>

for example I want child 1 opacity from 0 to 1 and then child 2 opacity from 0 to 1 then back to child 1 scale from 2 to 1

**Comment by bitworking** [comment]
It's now possible in the newest version. Thanks for this idea: https://bitworking.github.io/react-gsap/src-components-timeline#multiple-targets
