### ISSUE TITLE
Timeline is not reacting: GSAP target  not found

### ISSUE THREAD

**Issue by svenmalkus** [bitworking/react-gsap#38]
I can not get <Timeline> to work.

[https://codesandbox.io/s/stoic-water-ed68o?file=/src/App.js](https://codesandbox.io/s/stoic-water-ed68o?file=/src/App.js)

Tween is working as expected, but Timeline is not reacting. In the console are a bunch of "GSAP target not found" errors.

Any idea what i'm doing wrong?

Thanks a lot!

**Comment by bitworking** [comment]
With react < 17 it works. So there seems to be some code, that are not combatible with react 17, although I tought there were no breaking changes. I guess I have to test it with react 17.

**Comment by svenmalkus** [comment]
Ah, i see. Thanks for the hint!
In the meantime i found out, that react-gsap 3.0.0 is working with react 17.0.2.
I will try to use this version and upgrade later.

Thanks for your work!

**Comment by bitworking** [comment]
Thanks for reporting. Works with version 3.2.1.

**Comment by svenmalkus** [comment]
Wow! Thanks a lot for the fast response!
