### ISSUE TITLE
Control Tween Speed and Cycle

### ISSUE THREAD

**Issue by ericnguyen23** [bitworking/react-gsap#4]
How do I control the speed of Tween? 

I'm rotating a wheel and not sure how to control the speed. Here's the code:

```
<Tween
            directionalRotation={'360_ccw'}
            transformOrigin={'50% 50%'}
            repeat={500}
            ease={'Linear.easeNone'}
 >
```

Additionally, how would I repeat the tween infinitely? Currently, I'm using repeat and passing 500.

**Comment by bitworking** [comment]
Try with duration (in seconds) and repeat -1:

<Tween
            directionalRotation={'360_ccw'}
            transformOrigin={'50% 50%'}
            repeat={-1}
           duration={1}
            ease={'Linear.easeNone'}
 >
