### ISSUE TITLE
Add support for ScrollToPlugin

### ISSUE THREAD

**Issue by allan-walker** [bitworking/react-gsap#8]
Hey! Loving this project, thanks heaps!

Is it possible to add ScrollToPlugin to this? Even if you could just point me in the right direction of the steps involved to do this that would be great, I'm trying to implement this for a project at the moment.

**Comment by bitworking** [comment]
I didn't test it, but check out the new version and this docs: https://bitworking.github.io/react-gsap/src-plugins-gsap
